name: verify code style and run tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
<<<<<<< HEAD
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
=======
        run: npm ci
>>>>>>> 238fffd7169fe21e1f485d72fa7c3defba384111
      - name: Build deployment package
        run: npm run build